name: community-labeller

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues or pull requests
        uses: puppetlabs/community-labeller@v0
        with:
          label_name: community
          label_color: '5319e7'
          org_membership: puppetlabs
          token: ${{ secrets.IAC_COMMUNITY_LABELER }}

  test:
    name: Label Must Exist
    runs-on: ubuntu-latest
    steps:
      - name: Check for Labels
        uses: actions/github-script@v6
        with:
          script: |
            async function getPullRequest() {
              // Get current pull request labels
              const { data: { labels } } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.number,
              });

              // Log found label names
              for (const label of labels) {
                core.info(`Found label named '${label.name}' on pull request number ${context.payload.number}`);
              }

              // Fail workflow if no labels exist
              const labelsExist = labels.length > 0;
              if (!labelsExist) {
                core.setFailed(`Please ensure that a label exists on pull request number ${context.payload.number}`);
              }
            }

            await getPullRequest();
